"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from . import C14_cipher_pb2 as _C14_cipher_pb2
from . import C15_IV_pb2 as _C15_IV_pb2
from . import backup_expiry_pb2 as _backup_expiry_pb2
import builtins as _builtins
from . import key_type_pb2 as _key_type_pb2
from . import passkey_encryption_metadata_pb2 as _passkey_encryption_metadata_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class BackupPrefix(_message.Message):
    """
    This file describes the header you can find near the start of an encrypted backup file.

    The field names are WhatsApp's own. Fields 2 and 3 are not a oneof in the app: its message
    schema lists them as two ordinary optional fields, so a header may in principle set neither.
    """

    DESCRIPTOR: _descriptor.Descriptor

    KEY_TYPE_DEPRECATED_FIELD_NUMBER: _builtins.int
    WA_PROVIDED_KEY_DATA_FIELD_NUMBER: _builtins.int
    E2EE_KEY_DATA_FIELD_NUMBER: _builtins.int
    BACKUP_METADATA_FIELD_NUMBER: _builtins.int
    PASSKEY_ENCRYPTION_METADATA_FIELD_NUMBER: _builtins.int
    KEY_TYPE_NEW_FIELD_NUMBER: _builtins.int
    key_type_deprecated: _key_type_pb2.Key_Type.ValueType
    """Which of the two ciphers a backup uses is really told by whichever of fields 2 and 3 is
    set. This one has been deprecated in favour of key_type_new, but is still written.
    """
    key_type_new: _key_type_pb2.Key_Type.ValueType
    """What key_type_deprecated became once password and passkey backups arrived, and it was no
    longer enough to say only whether the key is end-to-end. Every crypt15 backup seen from
    WhatsApp 2.26 carries E2EE_ENCRYPTION_KEY here.
    """
    @_builtins.property
    def wa_provided_key_data(self) -> _C14_cipher_pb2.C14_cipher:
        """If DB is crypt14"""

    @_builtins.property
    def e2ee_key_data(self) -> _C15_IV_pb2.C15_IV:
        """If DB is crypt15"""

    @_builtins.property
    def backup_metadata(self) -> _backup_expiry_pb2.BackupExpiry:
        """Version that generated backup and other infos"""

    @_builtins.property
    def passkey_encryption_metadata(self) -> _passkey_encryption_metadata_pb2.PasskeyEncryptionMetadata: ...
    def __init__(
        self,
        *,
        key_type_deprecated: _key_type_pb2.Key_Type.ValueType | None = ...,
        wa_provided_key_data: _C14_cipher_pb2.C14_cipher | None = ...,
        e2ee_key_data: _C15_IV_pb2.C15_IV | None = ...,
        backup_metadata: _backup_expiry_pb2.BackupExpiry | None = ...,
        passkey_encryption_metadata: _passkey_encryption_metadata_pb2.PasskeyEncryptionMetadata | None = ...,
        key_type_new: _key_type_pb2.Key_Type.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["backup_metadata", b"backup_metadata", "e2ee_key_data", b"e2ee_key_data", "key_type_deprecated", b"key_type_deprecated", "key_type_new", b"key_type_new", "passkey_encryption_metadata", b"passkey_encryption_metadata", "wa_provided_key_data", b"wa_provided_key_data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["backup_metadata", b"backup_metadata", "e2ee_key_data", b"e2ee_key_data", "key_type_deprecated", b"key_type_deprecated", "key_type_new", b"key_type_new", "passkey_encryption_metadata", b"passkey_encryption_metadata", "wa_provided_key_data", b"wa_provided_key_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BackupPrefix: _TypeAlias = BackupPrefix  # noqa: Y015
