# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backup_prefix.proto
# Protobuf Python Version: 5.29.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    6,
    '',
    'backup_prefix.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import C14_cipher_pb2 as C14__cipher__pb2
from . import C15_IV_pb2 as C15__IV__pb2
from . import key_type_pb2 as key__type__pb2
from . import backup_expiry_pb2 as backup__expiry__pb2
from . import passkey_encryption_metadata_pb2 as passkey__encryption__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62\x61\x63kup_prefix.proto\x1a\x10\x43\x31\x34_cipher.proto\x1a\x0c\x43\x31\x35_IV.proto\x1a\x0ekey_type.proto\x1a\x13\x62\x61\x63kup_expiry.proto\x1a!passkey_encryption_metadata.proto\"\x8b\x02\n\x0c\x42\x61\x63kupPrefix\x12&\n\x13key_type_deprecated\x18\x01 \x01(\x0e\x32\t.Key_Type\x12)\n\x14wa_provided_key_data\x18\x02 \x01(\x0b\x32\x0b.C14_cipher\x12\x1e\n\re2ee_key_data\x18\x03 \x01(\x0b\x32\x07.C15_IV\x12&\n\x0f\x62\x61\x63kup_metadata\x18\x04 \x01(\x0b\x32\r.BackupExpiry\x12?\n\x1bpasskey_encryption_metadata\x18\x05 \x01(\x0b\x32\x1a.PasskeyEncryptionMetadata\x12\x1f\n\x0ckey_type_new\x18\x06 \x01(\x0e\x32\t.Key_Typeb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backup_prefix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKUPPREFIX']._serialized_start=128
  _globals['_BACKUPPREFIX']._serialized_end=395
# @@protoc_insertion_point(module_scope)
