"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class C14_cipher(_message.Message):
    """crypt14 cipher files."""

    DESCRIPTOR: _descriptor.Descriptor

    BACKUP_CIPHER_HEADER_FIELD_NUMBER: _builtins.int
    KEY_VERSION_FIELD_NUMBER: _builtins.int
    SERVER_SALT_FIELD_NUMBER: _builtins.int
    GOOGLE_ID_SALT_FIELD_NUMBER: _builtins.int
    ENCRYPTION_IV_FIELD_NUMBER: _builtins.int
    backup_cipher_header: _builtins.bytes
    """is usually 0001"""
    key_version: _builtins.bytes
    """Is usually "1" """
    server_salt: _builtins.bytes
    """The 32-bytes long server salt"""
    google_id_salt: _builtins.bytes
    """The 16-bytes long google id salt"""
    encryption_iv: _builtins.bytes
    """The 16-bytes long IV"""
    def __init__(
        self,
        *,
        backup_cipher_header: _builtins.bytes | None = ...,
        key_version: _builtins.bytes | None = ...,
        server_salt: _builtins.bytes | None = ...,
        google_id_salt: _builtins.bytes | None = ...,
        encryption_iv: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["backup_cipher_header", b"backup_cipher_header", "encryption_iv", b"encryption_iv", "google_id_salt", b"google_id_salt", "key_version", b"key_version", "server_salt", b"server_salt"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["backup_cipher_header", b"backup_cipher_header", "encryption_iv", b"encryption_iv", "google_id_salt", b"google_id_salt", "key_version", b"key_version", "server_salt", b"server_salt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___C14_cipher: _TypeAlias = C14_cipher  # noqa: Y015
