"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class C15_IV(_message.Message):
    """In crypt15 files only the IV is stored."""

    DESCRIPTOR: _descriptor.Descriptor

    ENCRYPTION_IV_FIELD_NUMBER: _builtins.int
    encryption_iv: _builtins.bytes
    """The 16-bytes long IV"""
    def __init__(
        self,
        *,
        encryption_iv: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["encryption_iv", b"encryption_iv"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encryption_iv", b"encryption_iv"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___C15_IV: _TypeAlias = C15_IV  # noqa: Y015
