# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: key_type.proto
# Protobuf Python Version: 5.29.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    6,
    '',
    'key_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekey_type.proto*n\n\x08Key_Type\x12\x0f\n\x0bWA_PROVIDED\x10\x00\x12\x13\n\x0f\x45\x32\x45\x45_DEPRECATED\x10\x01\x12\x11\n\rE2EE_PASSWORD\x10\x02\x12\x17\n\x13\x45\x32\x45\x45_ENCRYPTION_KEY\x10\x03\x12\x10\n\x0c\x45\x32\x45\x45_PASSKEY\x10\x04\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'key_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEY_TYPE']._serialized_start=18
  _globals['_KEY_TYPE']._serialized_end=128
# @@protoc_insertion_point(module_scope)
