"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _KeyType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _KeyTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_KeyType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    WA_PROVIDED: _KeyType.ValueType  # 0
    """WhatsApp holds the key: crypt12 and crypt14"""
    E2EE_DEPRECATED: _KeyType.ValueType  # 1
    """end-to-end, from before the kind of key was spelled out"""
    E2EE_PASSWORD: _KeyType.ValueType  # 2
    """derived from a user password"""
    E2EE_ENCRYPTION_KEY: _KeyType.ValueType  # 3
    """the 64-digit key: what crypt15 backups carry today"""
    E2EE_PASSKEY: _KeyType.ValueType  # 4
    """derived from a passkey"""

class KeyType(_KeyType, metaclass=_KeyTypeEnumTypeWrapper):
    """Both key type fields of BackupPrefix are verified against this one enum -- the app builds a
    single Internal$EnumVerifier and puts it at both positions in the message schema.
    The value names are WhatsApp's own; the enum's own name does not survive into the binary,
    so KeyType is this project's.
    """

WA_PROVIDED: KeyType.ValueType  # 0
"""WhatsApp holds the key: crypt12 and crypt14"""
E2EE_DEPRECATED: KeyType.ValueType  # 1
"""end-to-end, from before the kind of key was spelled out"""
E2EE_PASSWORD: KeyType.ValueType  # 2
"""derived from a user password"""
E2EE_ENCRYPTION_KEY: KeyType.ValueType  # 3
"""the 64-digit key: what crypt15 backups carry today"""
E2EE_PASSKEY: KeyType.ValueType  # 4
"""derived from a passkey"""
Global___KeyType: _TypeAlias = KeyType  # noqa: Y015
