"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Key_Type:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _Key_TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Key_Type.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    WA_PROVIDED: _Key_Type.ValueType  # 0
    """WhatsApp holds the key: crypt12 and crypt14"""
    E2EE_DEPRECATED: _Key_Type.ValueType  # 1
    """end-to-end, from before the kind of key was spelled out"""
    E2EE_PASSWORD: _Key_Type.ValueType  # 2
    """derived from a user password"""
    E2EE_ENCRYPTION_KEY: _Key_Type.ValueType  # 3
    """the 64-digit key: what crypt15 backups carry today"""
    E2EE_PASSKEY: _Key_Type.ValueType  # 4
    """derived from a passkey"""

class Key_Type(_Key_Type, metaclass=_Key_TypeEnumTypeWrapper):
    """Both key type fields of BackupPrefix are verified against this one enum -- the app builds a
    single Internal$EnumVerifier and puts it at both positions in the message schema.
    The value names are WhatsApp's own; the enum's own name does not survive into the binary,
    so Key_Type is this project's.
    """

WA_PROVIDED: Key_Type.ValueType  # 0
"""WhatsApp holds the key: crypt12 and crypt14"""
E2EE_DEPRECATED: Key_Type.ValueType  # 1
"""end-to-end, from before the kind of key was spelled out"""
E2EE_PASSWORD: Key_Type.ValueType  # 2
"""derived from a user password"""
E2EE_ENCRYPTION_KEY: Key_Type.ValueType  # 3
"""the 64-digit key: what crypt15 backups carry today"""
E2EE_PASSKEY: Key_Type.ValueType  # 4
"""derived from a passkey"""
Global___Key_Type: _TypeAlias = Key_Type  # noqa: Y015
