# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: passkey_encryption_metadata.proto
# Protobuf Python Version: 5.29.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    6,
    '',
    'passkey_encryption_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!passkey_encryption_metadata.proto\"\x84\x02\n\x19PasskeyEncryptionMetadata\x12\x1d\n\x15\x65ncapsulated_root_key\x18\x01 \x01(\t\x12 \n\x18\x63redential_id_deprecated\x18\x02 \x01(\t\x12\x1b\n\x13prf_salt_deprecated\x18\x03 \x01(\x0c\x12!\n\x19server_cypher_key_version\x18\x04 \x01(\t\x12&\n\x1eserver_cypher_key_account_salt\x18\x05 \x01(\x0c\x12%\n\x1dserver_cypher_key_server_salt\x18\x06 \x01(\x0c\x12\x17\n\x0f\x63lient_metadata\x18\x07 \x01(\x0c\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'passkey_encryption_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PASSKEYENCRYPTIONMETADATA']._serialized_start=38
  _globals['_PASSKEYENCRYPTIONMETADATA']._serialized_end=298
# @@protoc_insertion_point(module_scope)
