"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PasskeyEncryptionMetadata(_message.Message):
    """What a backup encrypted with a passkey carries instead of a bare IV. No backup this project
    has seen sets it -- it is here so the field is named rather than unknown.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ENCAPSULATED_ROOT_KEY_FIELD_NUMBER: _builtins.int
    CREDENTIAL_ID_DEPRECATED_FIELD_NUMBER: _builtins.int
    PRF_SALT_DEPRECATED_FIELD_NUMBER: _builtins.int
    SERVER_CYPHER_KEY_VERSION_FIELD_NUMBER: _builtins.int
    SERVER_CYPHER_KEY_ACCOUNT_SALT_FIELD_NUMBER: _builtins.int
    SERVER_CYPHER_KEY_SERVER_SALT_FIELD_NUMBER: _builtins.int
    CLIENT_METADATA_FIELD_NUMBER: _builtins.int
    encapsulated_root_key: _builtins.str
    credential_id_deprecated: _builtins.str
    prf_salt_deprecated: _builtins.bytes
    server_cypher_key_version: _builtins.str
    server_cypher_key_account_salt: _builtins.bytes
    server_cypher_key_server_salt: _builtins.bytes
    client_metadata: _builtins.bytes
    def __init__(
        self,
        *,
        encapsulated_root_key: _builtins.str | None = ...,
        credential_id_deprecated: _builtins.str | None = ...,
        prf_salt_deprecated: _builtins.bytes | None = ...,
        server_cypher_key_version: _builtins.str | None = ...,
        server_cypher_key_account_salt: _builtins.bytes | None = ...,
        server_cypher_key_server_salt: _builtins.bytes | None = ...,
        client_metadata: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["client_metadata", b"client_metadata", "credential_id_deprecated", b"credential_id_deprecated", "encapsulated_root_key", b"encapsulated_root_key", "prf_salt_deprecated", b"prf_salt_deprecated", "server_cypher_key_account_salt", b"server_cypher_key_account_salt", "server_cypher_key_server_salt", b"server_cypher_key_server_salt", "server_cypher_key_version", b"server_cypher_key_version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_metadata", b"client_metadata", "credential_id_deprecated", b"credential_id_deprecated", "encapsulated_root_key", b"encapsulated_root_key", "prf_salt_deprecated", b"prf_salt_deprecated", "server_cypher_key_account_salt", b"server_cypher_key_account_salt", "server_cypher_key_server_salt", b"server_cypher_key_server_salt", "server_cypher_key_version", b"server_cypher_key_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PasskeyEncryptionMetadata: _TypeAlias = PasskeyEncryptionMetadata  # noqa: Y015
