# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WAWebProtobufsAea.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'WAWebProtobufsAea.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17WAWebProtobufsAea.proto\x12\x11WAWebProtobufsAea\"\x94\x01\n\x12NonE2EEAttestation\x12\x46\n\x0b\x61\x63\x63ountType\x18\x01 \x01(\x0e\x32\x31.WAWebProtobufsAea.NonE2EEAttestation.AccountType\"6\n\x0b\x41\x63\x63ountType\x12\x08\n\x04\x45\x32\x45\x45\x10\x00\x12\x0f\n\x0bHYBRID_E2EE\x10\x01\x12\x0c\n\x08NON_E2EE\x10\x02\x42!Z\x1fgo.mau.fi/whatsmeow/proto/waAea')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WAWebProtobufsAea_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037go.mau.fi/whatsmeow/proto/waAea'
  _globals['_NONE2EEATTESTATION']._serialized_start=47
  _globals['_NONE2EEATTESTATION']._serialized_end=195
  _globals['_NONE2EEATTESTATION_ACCOUNTTYPE']._serialized_start=141
  _globals['_NONE2EEATTESTATION_ACCOUNTTYPE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
