# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WAWebProtobufsUserPassword.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'WAWebProtobufsUserPassword.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n WAWebProtobufsUserPassword.proto\x12\x1aWAWebProtobufsUserPassword\"\xa7\x04\n\x0cUserPassword\x12\x43\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32\x31.WAWebProtobufsUserPassword.UserPassword.Encoding\x12I\n\x0btransformer\x18\x02 \x01(\x0e\x32\x34.WAWebProtobufsUserPassword.UserPassword.Transformer\x12O\n\x0etransformerArg\x18\x03 \x03(\x0b\x32\x37.WAWebProtobufsUserPassword.UserPassword.TransformerArg\x12\x17\n\x0ftransformedData\x18\x04 \x01(\x0c\x1a\xac\x01\n\x0eTransformerArg\x12\x0b\n\x03key\x18\x01 \x01(\t\x12L\n\x05value\x18\x02 \x01(\x0b\x32=.WAWebProtobufsUserPassword.UserPassword.TransformerArg.Value\x1a?\n\x05Value\x12\x10\n\x06\x61sBlob\x18\x01 \x01(\x0cH\x00\x12\x1b\n\x11\x61sUnsignedInteger\x18\x02 \x01(\rH\x00\x42\x07\n\x05value\"G\n\x0bTransformer\x12\x08\n\x04NONE\x10\x00\x12\x16\n\x12PBKDF2_HMAC_SHA512\x10\x01\x12\x16\n\x12PBKDF2_HMAC_SHA384\x10\x02\"%\n\x08\x45ncoding\x12\x08\n\x04UTF8\x10\x00\x12\x0f\n\x0bUTF8_BROKEN\x10\x01\x42*Z(go.mau.fi/whatsmeow/proto/waUserPassword')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WAWebProtobufsUserPassword_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(go.mau.fi/whatsmeow/proto/waUserPassword'
  _globals['_USERPASSWORD']._serialized_start=65
  _globals['_USERPASSWORD']._serialized_end=616
  _globals['_USERPASSWORD_TRANSFORMERARG']._serialized_start=332
  _globals['_USERPASSWORD_TRANSFORMERARG']._serialized_end=504
  _globals['_USERPASSWORD_TRANSFORMERARG_VALUE']._serialized_start=441
  _globals['_USERPASSWORD_TRANSFORMERARG_VALUE']._serialized_end=504
  _globals['_USERPASSWORD_TRANSFORMER']._serialized_start=506
  _globals['_USERPASSWORD_TRANSFORMER']._serialized_end=577
  _globals['_USERPASSWORD_ENCODING']._serialized_start=579
  _globals['_USERPASSWORD_ENCODING']._serialized_end=616
# @@protoc_insertion_point(module_scope)
