# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WAWebProtobufsChatLockSettings.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'WAWebProtobufsChatLockSettings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WAWebProtobufsUserPassword_pb2 as WAWebProtobufsUserPassword__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$WAWebProtobufsChatLockSettings.proto\x12\x1eWAWebProtobufsChatLockSettings\x1a WAWebProtobufsUserPassword.proto\"i\n\x10\x43hatLockSettings\x12\x17\n\x0fhideLockedChats\x18\x01 \x01(\x08\x12<\n\nsecretCode\x18\x02 \x01(\x0b\x32(.WAWebProtobufsUserPassword.UserPasswordB.Z,go.mau.fi/whatsmeow/proto/waChatLockSettings')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WAWebProtobufsChatLockSettings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,go.mau.fi/whatsmeow/proto/waChatLockSettings'
  _globals['_CHATLOCKSETTINGS']._serialized_start=106
  _globals['_CHATLOCKSETTINGS']._serialized_end=211
# @@protoc_insertion_point(module_scope)
