# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: C14_cipher_version.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43\x31\x34_cipher_version.proto\"%\n\x12\x43\x31\x34_cipher_version\x12\x0f\n\x07version\x18\x01 \x01(\x05\x62\x06proto3')



_C14_CIPHER_VERSION = DESCRIPTOR.message_types_by_name['C14_cipher_version']
C14_cipher_version = _reflection.GeneratedProtocolMessageType('C14_cipher_version', (_message.Message,), {
  'DESCRIPTOR' : _C14_CIPHER_VERSION,
  '__module__' : 'C14_cipher_version_pb2'
  # @@protoc_insertion_point(class_scope:C14_cipher_version)
  })
_sym_db.RegisterMessage(C14_cipher_version)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _C14_CIPHER_VERSION._serialized_start=28
  _C14_CIPHER_VERSION._serialized_end=65
# @@protoc_insertion_point(module_scope)
