# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: C15_IV.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x43\x31\x35_IV.proto\"\x10\n\x02IV\x12\n\n\x02IV\x18\x01 \x01(\x0c\x62\x06proto3')



_IV = DESCRIPTOR.message_types_by_name['IV']
IV = _reflection.GeneratedProtocolMessageType('IV', (_message.Message,), {
  'DESCRIPTOR' : _IV,
  '__module__' : 'C15_IV_pb2'
  # @@protoc_insertion_point(class_scope:IV)
  })
_sym_db.RegisterMessage(IV)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IV._serialized_start=16
  _IV._serialized_end=32
# @@protoc_insertion_point(module_scope)
