# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: C15_header.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.C15_IV_pb2 as C15__IV__pb2
import proto.C15_metadata_pb2 as C15__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43\x31\x35_header.proto\x1a\x0c\x43\x31\x35_IV.proto\x1a\x12\x43\x31\x35_metadata.proto\"b\n\rCrypt15Prefix\x12\x1b\n\x08key_type\x18\x01 \x01(\x0e\x32\t.Key_Type\x12\x0f\n\x02iv\x18\x03 \x01(\x0b\x32\x03.IV\x12#\n\x04info\x18\x04 \x01(\x0b\x32\x15.BackupVersionandInfo*/\n\x08Key_Type\x12\x0f\n\x0bWA_PROVIDED\x10\x00\x12\x12\n\x0eHSM_CONTROLLED\x10\x01\x62\x06proto3')

_KEY_TYPE = DESCRIPTOR.enum_types_by_name['Key_Type']
Key_Type = enum_type_wrapper.EnumTypeWrapper(_KEY_TYPE)
WA_PROVIDED = 0
HSM_CONTROLLED = 1


_CRYPT15PREFIX = DESCRIPTOR.message_types_by_name['Crypt15Prefix']
Crypt15Prefix = _reflection.GeneratedProtocolMessageType('Crypt15Prefix', (_message.Message,), {
  'DESCRIPTOR' : _CRYPT15PREFIX,
  '__module__' : 'C15_header_pb2'
  # @@protoc_insertion_point(class_scope:Crypt15Prefix)
  })
_sym_db.RegisterMessage(Crypt15Prefix)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEY_TYPE._serialized_start=154
  _KEY_TYPE._serialized_end=201
  _CRYPT15PREFIX._serialized_start=54
  _CRYPT15PREFIX._serialized_end=152
# @@protoc_insertion_point(module_scope)
